"""empty message

Revision ID: 8fc0b5b2c3a3
Revises: b663a7e4a400
Create Date: 2024-07-15 00:42:55.130064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc0b5b2c3a3'
down_revision: Union[str, None] = 'b663a7e4a400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('full_description', sa.String(), nullable=False))
    op.add_column('products', sa.Column('short_description', sa.String(), nullable=False))
    op.alter_column('products', 'prise',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('products', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('products', 'prise',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('products', 'short_description')
    op.drop_column('products', 'full_description')
    # ### end Alembic commands ###
