"""empty message

Revision ID: 27e4dd31e560
Revises: c1ed56059cf4
Create Date: 2024-07-27 19:29:04.324600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e4dd31e560'
down_revision: Union[str, None] = 'c1ed56059cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_published', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('photos', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.alter_column('photos', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'photos', 'blog', ['blog_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.alter_column('photos', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('photos', 'blog_id')
    op.drop_table('blog')
    # ### end Alembic commands ###
