"""empty message

Revision ID: 72b303c77544
Revises: 6dd7832f97d9
Create Date: 2024-07-19 23:30:13.302314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b303c77544'
down_revision: Union[str, None] = '6dd7832f97d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
