"""empty message

Revision ID: c1ed56059cf4
Revises: 72b303c77544
Create Date: 2024-07-25 01:24:22.954782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ed56059cf4'
down_revision: Union[str, None] = '72b303c77544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('products', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('products', 'prise')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('prise', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('products', 'price')
    op.alter_column('admins', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
